name: "HCL AppScan SAST"
on:
  #workflow_dispatch
  pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create config file
        run: bash ./create_config_file.sh
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.7
        with:
          service_url: https://eu.cloud.appscan.com
          asoc_key: ${{secrets.EU_ASOC_KEY}}
          asoc_secret: ${{secrets.EU_ASOC_SECRET}}
          application_id: ${{vars.ASOC_APPID}}
          wait_for_analysis: true
          fail_for_noncompliance: true

